server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: {clientId }
            client-secret: {ClientSecret}

jwt:
  header: Authorization
  secretKey: {secretKey}
## secret 키는 절대 github에 올리면 안됨. 대참사일어남.

